spring.application.name=Restaurant_management


server.port=${PORT:8080}


spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/restaurent_management}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:123456789}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false


jwt.signerKey=${JWT_SIGNER_KEY:KiPcgWahgz6NceGrW6EfCgFGpsfeqgCbHzr7tdItAni0cAdVOwWRTISeXvRDx5bh}
jwt.access-duration=${JWT_ACCESS_DURATION:604800}
jwt.context-duration=${JWT_CONTEXT_DURATION:28800}