spring.application.name=Restaurant_management
spring.datasource.url=jdbc:mysql://localhost:3306/restaurent_management
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



jwt.signerKey = KiPcgWahgz6NceGrW6EfCgFGpsfeqgCbHzr7tdItAni0cAdVOwWRTISeXvRDx5bh

jwt.access-duration=604800
jwt.context-duration=28800